### ISSUE TITLE
does not open application in windows 11

### ISSUE THREAD

**Issue by rsierrag** [nmonvisualizer/nmonvisualizer#104]
app nmonvisualizer does not open in windows 11 does not give any answer

**Comment by hpresnall** [comment]
What version of the JVM are you using?
If you run `java -jar NMONVisualizer_<release_date>.jar` from the command line, are there any errors?

**Comment by rsierrag** [comment]
I get this error when I run the command

 01/04/2024   14:58.23   /home/mobaxterm/Desktop  java -jar NMONVisualizer_2024-02-29.jar
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.awt.Toolkit.getMenuShortcutKeyMaskEx()I
        at com.ibm.nmon.gui.main.MainMenu.createFileMenu(MainMenu.java:84)
        at com.ibm.nmon.gui.main.MainMenu.<init>(MainMenu.java:65)
        at com.ibm.nmon.gui.main.NMONVisualizerGui.<init>(NMONVisualizerGui.java:173)
        at com.ibm.nmon.gui.main.NMONVisualizerGui$1.run(NMONVisualizerGui.java:77)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
