### ISSUE TITLE
MacOS 15.1.1 (24B91)

### ISSUE THREAD

**Issue by zanglikun** [nmonvisualizer/nmonvisualizer#110]
2024-12-20 11:59:44.809 java[51467:12163217] +[IMKInputSession subclass]: chose IMKInputSession_Modern
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.awt.Toolkit.getMenuShortcutKeyMaskEx()I
	at com.ibm.nmon.gui.main.MainMenu.createFileMenu(MainMenu.java:84)
	at com.ibm.nmon.gui.main.MainMenu.<init>(MainMenu.java:65)
	at com.ibm.nmon.gui.main.NMONVisualizerGui.<init>(NMONVisualizerGui.java:173)
	at com.ibm.nmon.gui.main.NMONVisualizerGui$1.run(NMONVisualizerGui.java:77)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hpresnall** [comment]
I think this is a duplicate of #104 
Can you run with Java 11?

**Comment by zanglikun** [comment]
JDK11 IS OK。
  Can you add a multilingual module?

**Comment by hpresnall** [comment]
While Java Swing and JFree chart support i18n, NMONVisualizer was not programmed with that in mind. It would be a large effort to add and support this feature, especially when this program is in maintenance mode. If you want to do the work yourself or work with others to do it, I would be happy to accept a pull request.
