### ISSUE TITLE
Please help with date interval

### ISSUE THREAD

**Issue by greendruid** [nmonvisualizer/nmonvisualizer#22]
Hi,

Please, tell more about commandline switches '-s' & '-e'  and post some examples.

With best regards,
greendruid

**Comment by hpresnall** [comment]
The format is `yyyy-MM-ddTHH:mm:ssX` and follows the Java `SimpleDateFormat` syntax. So -s or -e can be something like `2015-01-22T16:00:00-01`. Just make sure end is greater than the start.

**Comment by greendruid** [comment]
# Thanks! 
**But I have an error:( I try to exec this:**
```bash
 java -jar nmon_vis.jar -s 2015-05-20T00:00:00+1 -e 2015-05-21T00:00:00+1 com.ibm.nmon.ReportGenerator --nodata -a k.xml ../tmp.
```
**and got an error message**:
```java
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: -s
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:19)
        ... 5 more
```
**What's wrong?**

**Comment by hpresnall** [comment]
You need to run `java -jar nmon_vis.jar  com.ibm.nmon.ReportGenerator -s ...`.

Note the ReportGenerator class name. This is needed to tell the runnable jar what the main class name is. If you wanted to change this, it's possible to directly call ReportGenerator by editing the MANIFEST.MF in the jar file. Change the `Rsrc-Main-Class` entry to `com.ibm.nmon.ReportGenerator`.
