### ISSUE TITLE
error parsing topasout csv file

### ISSUE THREAD

**Issue by yediortali** [nmonvisualizer/nmonvisualizer#37]
After converting topas file to csv file (with topasout -a file.topas) and then sorting it with sort command, trying to analyze the file with nmon visualizer throws the following error message. nmon analyzer (excel) is perfectly capable of analyzing the same file.

SEVERE could not parse ...
java.lang.IllegalArgumentException: cannot redefine DataType CPU00 within the same data set
  at com.ibm.nmon.data.DataSet.AddType(DataSet.java:70)
  at com.ibm.nmon.parser.NMONParser.parseHeaders(NMONParser.java:247)
  at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:85)
  at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:66)
  at com.ibm.nmon.parser.NMONParser.parse(NMONVisualizerApp.java:139)
  at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
  at java.langThread.run(Thread.java:745)

**Comment by pluto00987** [comment]
This got me too. The wrong parser is getting called. Make sure your topasrec filename doesn't contain 'nmon' nor end in '.csv'. That fixed it for me.

**Comment by AlexIvamoto** [comment]
topasout -a file_topasrec next rename out file with *csv to not end csv. This fixed for me too.
