### ISSUE TITLE
iostat parsing problem

### ISSUE THREAD

**Issue by Rexikon** [nmonvisualizer/nmonvisualizer#39]
i have used command 

`iostat -tNxm 1 5 > iotop.log`

next i have to load in NMONVisualizer but program tells me:

```
/home/rexikon/tmp/iostat.log:
SEVERE  could not parse /home/rexikon/tmp/iostat.log
java.lang.NumberFormatException: For input string: "5,14"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.parseDouble(Double.java:540)
    at com.ibm.nmon.parser.IOStatParser.parseLinuxCPU(IOStatParser.java:495)
    at com.ibm.nmon.parser.IOStatParser.parse(IOStatParser.java:145)
    at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:160)
    at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
    at java.lang.Thread.run(Thread.java:745)

```

What should I do ?

**Comment by hpresnall** [comment]
Is this localization related? Is your iostat output in #,## numeric output but your Java local is English so it's expecting #.## numbers?

**Comment by hpresnall** [comment]
Latest commits should handle this as long as the locale of the JVM running NMONVisualizer is the same as the locale where iostat was collected. JVM can set set by running with flags like `-Duser.language=fr -Duser.language=FR`
