### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 13

### ISSUE THREAD

**Issue by bef1** [nmonvisualizer/nmonvisualizer#45]
I am running the following nmon command on an AIX 6.1 server:

/usr/bin/topas_nmon -F /home/whatever/file.nmon -T -r hostname -s30 -c2633 -youtput_dir=/var/somefile.nmon -ystart_time=02:00:04,Jul12,2017

When I try to parse the file with NMONVisualizer, I get the following error:

/some-path/nmon3.nmon:
SEVERE  could not parse /some-path/nmon3.nmon
java.lang.ArrayIndexOutOfBoundsException: 13
	at com.ibm.nmon.parser.NMONParser.parseTopData(NMONParser.java:585)
	at com.ibm.nmon.parser.NMONParser.parseLine(NMONParser.java:311)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:98)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:66)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:139)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

Any idea what might explain this issue?

**Comment by hpresnall** [comment]
Did the file get truncated? That error would happen if there is data for `TOP` in the file _before_ there was a `TOP` header record.

Do you have sample data you can send or was this not repeatable?
