### ISSUE TITLE
I have trie to run NMONVisualizer in Mac OS Sierra 10.13 and I have an issue 

### ISSUE THREAD

**Issue by ralejandrog** [nmonvisualizer/nmonvisualizer#51]
I have trie to run NMONVisualizer in Mac OS Sierra 10.13 andava version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode) and I have an issue:
 # java -jar NMONVisualizer_2017-08-08.jar.  
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)

Could you please help me to fix this issue !

**Comment by hpresnall** [comment]
I am guessing this is similar to #48. If you can, try and build the latest commit and see if that works.
I am overdue for creating a new release and can do that in the next day or two.

**Comment by ralejandrog** [comment]
I try to run  as per the comments in #48 but not luck  i think is regarding  with a missing class cause i had the same  msg error:
Note: Just to mention i zunziped the java jar and  then i used this command:

java -cp 'NMONVisualizer_2017-08-08.jar:./*' com.ibm.nmon.DelegatingMain
Exception in thread "main" java.lang.ClassNotFoundException: com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2036)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:631)
	at com.ibm.nmon.gui.main.NMONVisualizerGui.main(NMONVisualizerGui.java:53)
	at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:14)

**Comment by ralejandrog** [comment]
Totally Happy it is working fine! HPRESNALL
