### ISSUE TITLE
iostat java.util.NoSuchElementException

### ISSUE THREAD

**Issue by Honghe** [nmonvisualizer/nmonvisualizer#53]
Environment:
* Ubuntu 16.04
* NMONVisualizer_2017-08-08
* iostat sysstat version 10.1.5

```
./perf_share (copy)/hadoop6_iostat_sdb:
WARNING  no fields defined for sdb; data will be ignored
SEVERE  could not parse ./perf_share (copy)/hadoop6_iostat_sdb
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at com.ibm.nmon.data.DataSet.getStartTime(DataSet.java:156)
	at com.ibm.nmon.NMONVisualizerApp.recalculateMinAndMaxSystemTime(NMONVisualizerApp.java:459)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:262)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Thread.java:748)
```
data sample of file hadoop6_iostat_sdb
```
Linux 3.10.0-693.el7.x86_64 (hadoop6) 	2018-04-19 	_x86_64_	(32 CPU)

2018-04-19T04:38:15-0400
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.01     0.66    1.81    0.77     0.23     0.38   483.44     0.42  163.69   15.53  514.96   1.78   0.46

2018-04-19T04:38:17-0400
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

**Comment by Honghe** [comment]
It works
