### ISSUE TITLE
Parsing .log file gives errors 

### ISSUE THREAD

**Issue by akankshajain** [nmonvisualizer/nmonvisualizer#55]
I am using `jre-8u181-windows-x64` and I have a log file which I am trying to parse using nmon visualiser.

```
I loaded the log file using the  GUI and here is the error I keep getting
```

and the logs show:
```
SEVERE  could not parse C:\Users\xyz\Db2wh_local_m-hlmokby.log
java.lang.IllegalArgumentException: filename must be formatted as 'identifier_yyyyddMM_HHmmss_type.log'
	at com.ibm.nmon.parser.FIOParser.parse(FIOParser.java:73)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:226)
	at com.ibm.nmon.ReportGenerator.parse(ReportGenerator.java:379)
	at com.ibm.nmon.ReportGenerator.main(ReportGenerator.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:37)
```

After renaming the file to `Db2wh_20182509_210500_type.log` as per suggestion I get:

```
SEVERE  could not parse C:/Users/akanksha_jain/Documents/Db2wh_20182509_210500_type.log
java.lang.IllegalArgumentException: unrecoginized type name 'TYPE' ; valid values are [SLAT, CLAT, IOPS, BW, LAT]
	at com.ibm.nmon.parser.FIOParser.parse(FIOParser.java:97)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:226)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)
```

I am not sure what is SLAT,CLAT,IOPS,BW,LAT and what is identifier? I used `Db2wh` randomly

**Comment by hpresnall** [comment]
If this is an NMON file, change the extension from `log` to `nmon` or put `nmon` somewhere in the file name.

All the parser matching is done by filename, the code does not analyze the contents of the file before processing. See [the file matching code](https://github.com/nmonvisualizer/nmonvisualizer/tree/master/src/com/ibm/nmon/file).
