### ISSUE TITLE
Cannot reproduce PROC chart

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#64]
I would like to make a custom chart like the PROC chart from NMON Analyser, using this XML:

<?xml version="1.0" encoding="UTF-8"?>

<charts>

  <linechart name="Processes"
             shortName="Run Queue" >

    <yAxis label="Queue Length" />

    <data>
      <host os="UNIX" />
      <type name="PROC" />

      <field name="Runnable" alias="RunQueue" />
      <field name="Swap-in" />
    </data>

  </linechart>

</charts>

What is wrong with my XML ? I get this error:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
        at java.lang.reflect.Method.invoke(Method.java:620)
        at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:37)
Caused by: java.lang.StringIndexOutOfBoundsException
        at java.lang.String.substring(String.java:1247)
        at com.ibm.nmon.parser.BasicXMLParser.parse(BasicXMLParser.java:141)
        at com.ibm.nmon.parser.BasicXMLParser.parse(BasicXMLParser.java:27)
        at com.ibm.nmon.chart.definition.ChartDefinitionParser.parseCharts(ChartDefinitionParser.java:49)
        at com.ibm.nmon.report.ReportCache.addReport(ReportCache.java:82)
        at com.ibm.nmon.ReportGenerator.parseChartDefinition(ReportGenerator.java:488)
        at com.ibm.nmon.ReportGenerator.<init>(ReportGenerator.java:406)
        at com.ibm.nmon.ReportGenerator.main(ReportGenerator.java:270)
        ... 5 more

**Comment by scbray1** [comment]
Oh. My XML wasn't pasted properly. Here it is again (as a text file, as drag and drop of an XML file was not allowed):
[PROC2.txt](https://github.com/nmonvisualizer/nmonvisualizer/files/2817440/PROC2.txt)
