### ISSUE TITLE
Error parsing nmon files for SUMMARY lines

### ISSUE THREAD

**Issue by snarkbe** [nmonvisualizer/nmonvisualizer#68]
I run the following command on an AIX 6.1 system:
`0 0 * * * /usr/bin/nmon -f -D -E -Y -W -P -d -N -^ -m /var/adm/nmon -s 60 -c 1439`

When I analyse the logs produced by this command, I get an error with NMONVisualizer_2019-01-06.jar : 

```
WARNING  T0001: invalid numeric data 'BESClient' at line 2126, column 10
WARNING  T0001: invalid numeric data 'java' at line 2127, column 10
WARNING  T0001: invalid numeric data 'wait' at line 2128, column 10
WARNING  T0001: invalid numeric data 'kuxagent' at line 2129, column 10
WARNING  T0001: invalid numeric data 'reaffin' at line 2130, column 10
WARNING  T0001: invalid numeric data 'kynagent' at line 2131, column 10
WARNING  T0001: invalid numeric data 'syncd' at line 2132, column 10
WARNING  T0001: invalid numeric data 'Swapper' at line 2133, column 10
WARNING  T0001: invalid numeric data 'gil = TCP/IP' at line 2134, column 10
WARNING  T0001: invalid numeric data 'swapper' at line 2135, column 10
WARNING  T0001: invalid numeric data '.vasd' at line 2136, column 10
WARNING  T0001: invalid numeric data 'nfssync_kproc' at line 2137, column 10 
....
```
The error log generated when running NMONVisualizer in command line mode has 140000 lines.
The command does not produce any graph. And it stops when running in interactive mode.

When I run the same command with an older version (NMONVisualizer_2018-04-10.jar), I get 1 error:

```
c:\temp\servername_190311_0000.nmon:
WARNING  T0001: invalid numeric data 'BESClient' at line 2126, column 10
WARNING  T0001: invalid numeric data 'java' at line 2127, column 10
WARNING  T0001: DataType SUMMARY defines 8 fields but there are only 8 values; missing values set to 0
SEVERE  could not parse c:\temp\servername_190311_0000.nmon
java.lang.IllegalArgumentException: DataType SUMMARY already defined for timestamp T0001
	at com.ibm.nmon.data.DataRecord.addData(DataRecord.java:74)
	at com.ibm.nmon.parser.NMONParser.parseData(NMONParser.java:540)
	at com.ibm.nmon.parser.NMONParser.parseLine(NMONParser.java:332)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:98)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:66)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:144)
	at com.ibm.nmon.ReportGenerator.parse(ReportGenerator.java:434)
	at com.ibm.nmon.ReportGenerator.main(ReportGenerator.java:314)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:37)
```

The lines it tries to parse are:

```
2125: SUMMARY,Summary of Processes,Processes,%usr,%sys,ResTextKB,ResDataKB,CharIOKB,paging,Command
2126: SUMMARY,T0001,1,1.605,0.470,20932,21576,924,0,BESClient
2127: SUMMARY,T0001,7,2.269,1.034,2664,2778136,35,0,java
2128: SUMMARY,T0001,24,0.003,6.180,0,1440,0,0,wait
```

(line number and colon added by me to match the error line in the error message)

I run NMONVisualizer on Windows 10, using Java 10:

```
C:\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
C:\>java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by hpresnall** [comment]
This looks like a new data type. The standard parsing expects all data after the first 2 columns to be numeric. I will need to write custom handler code for `SUMMARY` that handles the process name at the end.

I am not sure why you aren't seeing any data from the command line; the current WARNING messages shouldn't effect parsing of other data. Are you sure there isn't some other error in the log?
The stall in the GUI is probably because it's runs out of memory / heap space since the program keeps all the log lines in a dialog in memory.

For a temporary workaround, run the nmon files through `grep -v SUMMARY` to strip all those lines out and they should process OK.

**Comment by snarkbe** [comment]
Indeed it doesn't block the command-line mode. Here's the output for the 2 version of NMONVisualizer I have.

```
C:\Temp>java -jar NMONVisualizer_2019-01-06.jar com.ibm.nmon.ReportGenerator servername_190311_0000.nmon
Parsing NMON files...
        C:\Temp\servername_190311_0000.nmon... Complete with errors!
Parsing complete!

Errors written to ReportGenerator_20190314_153938.log

Charting interval All Data
Writing charts to C:\Temp\charts
Charts complete!
```

```
C:\Temp>java -jar NMONVisualizer_2018-04-10.jar com.ibm.nmon.ReportGenerator servername_190311_0000.nmon
Parsing NMON files...
        C:\Temp\servername_190311_0000.nmon... Complete with errors!
Parsing complete!

Errors written to ReportGenerator_20190314_154007.log

Charting interval All Data: 00:01:09 mars 11 - 23:59:37 mars 11
Writing charts to C:\Temp\charts
        Creating summary charts ........... Complete (11/11)
        Creating charts for servername ..................... Complete (21/21)
Charts complete!
```

The workaround of excluding the SUMMARY lines from the nmon logs works fine.

**Comment by hpresnall** [comment]
Please try parsing your files now without removing the SUMMARY lines.

**Comment by snarkbe** [comment]
It works fine with the latest version compiled from master. 
No problem parsing the files, and it shows correctly in the GUI. Thanks a lot!
