### ISSUE TITLE
error parsing topasout file 2019

### ISSUE THREAD

**Issue by fredriklundholm** [nmonvisualizer/nmonvisualizer#69]
In the latest nmon visualizer the data files get:

SEVERE  could not parse C:/Users/xxxxxx/1_190501.topas
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.ibm.nmon.parser.TopasOutParser.parse(TopasOutParser.java:59)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:144)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

However using 2015 version the files import fine. Regression.
[error1.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/3151742/error1.zip)

**Comment by hpresnall** [comment]
This file looks like it's binary. NMONVisualizer needs the text format. Did you run this topas file through `topasout -a`?
