### ISSUE TITLE
Cannot process json files from latest njmon 

### ISSUE THREAD

**Issue by MrGitBlob** [nmonvisualizer/nmonvisualizer#85]
Using NMONVisualizer_2020-02-29.jar
to load json file produced by njmon_RHEL8_x86_64_v71

I get this:

SEVERE  could not parse C:/Data/HN/Tools/NMONVisualizer/json/audccfots812_20210108_1408-from-njmon-71.json
java.io.IOException: field 'hostname' not found
	at com.ibm.nmon.parser.JSONParser.parse(JSONParser.java:49)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:208)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

pls halp :-(

**Comment by hpresnall** [comment]
If this came from NJMon, I am sorry, but it is not currently supported. Only CSV formatted NMON files from the original tool can be parsed right now.

There are other, newer tools for parsing njmon files.
