### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by avoskov** [nmonvisualizer/nmonvisualizer#86]
SEVERE could not parse /home/voskov.anton/Downloads/fis-host3_201123_1230.nmon
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.ibm.nmon.parser.NMONParser.parseTopFields(NMONParser.java:597)
at com.ibm.nmon.parser.NMONParser.parseHeaders(NMONParser.java:197)
at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:87)
at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:68)
at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:149)
at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
at java.base/java.lang.Thread.run(Thread.java:834)

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

**Comment by avoskov** [comment]
bad fis-host3_201123_1230.nmon file
