### ISSUE TITLE
esxtop data parsing error

### ISSUE THREAD

**Issue by vmMarkA** [nmonvisualizer/nmonvisualizer#87]
[Thank you for an amazing visualization tool! It has been very handy for esxtop data.]

When trying to parse esxtop data, I'm getting the following error:

/Users/markachtemichuk/Desktop/esxtop_output-firstrun/nomsdb101-esxi-23420_outputfile.csv:

SEVERE  could not parse /Users/markachtemichuk/Desktop/esxtop_output-firstrun/nomsdb101-esxi-23420_outputfile.csv
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:711)
	at com.ibm.nmon.parser.PerfmonParser.parseDouble(PerfmonParser.java:349)
	at com.ibm.nmon.parser.PerfmonParser.parseData(PerfmonParser.java:288)
	at com.ibm.nmon.parser.PerfmonParser.parse(PerfmonParser.java:71)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:231)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.base/java.lang.Thread.run(Thread.java:832)

Can you help me narrow down whats happening here? I'm using version 2020-02-29. I've attached the file I'm trying to parse.
[nomsdb101-esxi-23420_outputfile.csv.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/5858463/nomsdb101-esxi-23420_outputfile.csv.zip)

**Comment by hpresnall** [comment]
These esxtop files have a lot of columns, it's very hard to look at them in any editor. But, it seems like this file has either empty strings or non-number data in a few spots.

The patch I submitted works on the file you attached. If you can build from source and try some other files to confirm, that would be great.

**Comment by vmMarkA** [comment]
Thank you. I’m having trouble building from source (newbie here). Any chance you can share a build with me? Sorry, Thanks.

**Comment by vmMarkA** [comment]
Working now.

**Comment by vmMarkA** [comment]
Working now....Thnx!
