### ISSUE TITLE
Loading a NMON data and get error

### ISSUE THREAD

**Issue by Alianal** [nmonvisualizer/nmonvisualizer#96]
When I try to open an NMON data it pop up "Parsing Errors" window with this message 

WARNING  version header '{0}' is not in the right format, the time zone will default to UTC
SEVERE  could not parse nmon.csv 
java.lang.illegalArgumentException: hostname not found in 'progname'
                        at com.ibm.nmon.parser.PerfmonParser.parseHeader(PerfmonParser.java:184)
                        at com.ibm.nmon.parser.PerfmonParser.parse(PerfmonParser.java:79)
                        at com.ibm.nmon.NMONVisualsizerApp.parse(NMONVisualizerapp.java:231)
                        at java.lang.Thread.run(Unknown Source)

What could be the issue ?

**Comment by hpresnall** [comment]
Looks like the file is being parsed as a PerfMon file. Change the extension from `.csv` to `.nmon` and try again.

**Comment by Alianal** [comment]
Awesome
The nmon data can be loaded successfully after renaming the extension 
Thank You so much
