### ISSUE TITLE
SEVERE  could not parse *.nmon java.lang.ArrayIndexOutOfBoundsException: 13

### ISSUE THREAD

**Issue by angeleliseo** [nmonvisualizer/nmonvisualizer#98]
When trying to parse the nmon file attached 
[uvdesk_231103_1126.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/13256138/uvdesk_231103_1126.zip)

I got the follwing error:

*.nmon:
SEVERE  could not parse *.nmon
java.lang.ArrayIndexOutOfBoundsException: 13
	at com.ibm.nmon.parser.NMONParser.parseTopData(NMONParser.java:621)
	at com.ibm.nmon.parser.NMONParser.parseLine(NMONParser.java:317)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:100)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:68)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:149)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

---

The same file was able to be opened with NMon Analyzer

**Comment by hpresnall** [comment]
Looks like the file was truncated. Remove the last line and it should parse.

**Comment by angeleliseo** [comment]
I confirm that solved the parse issue, I am going to close this one.
